openapi: 3.0.0
info:
  title: API med_ml сервера
  description: API для сервера med_ml
  version: "v0.0.1"
servers:
  - url: http://localhost:8080/api/v1
    description: Local development server

components:
  schemas:
    device:
      type: object
      description: узи аппарат
      required:
        - id
        - name
      properties:
        id:
          type: integer
          description: id устройства
        name:
          type: string
          maxLength: 255
          description: название устройства
      example:
        id: 1
        name: "ульпанатор 3000"

    uzi:
      type: object
      description: узи
      required:
        - id
        - projection
        - checked
        - external_id
        - device_id
        - status
        - create_at
      properties:
        id:
          type: string
          format: uuid
          description: id узи
        projection:
          type: string
          description: проекция узи
          maxLength: 255
        checked:
          type: boolean
          description: проверенно ли врачем
        external_id:
          type: integer
          format: uuid
          description: id пациента/организации etc. Внешняя связсь
        device_id:
          type: integer
          description: id устройства
        status:
          type: string
          enum:
            - new
            - pending
            - completed
          description: >
            Статус узи
            **new** - новое узи
            **pending** - в обработке нейронкой
            **completed** - обработано
        create_at:
          type: string
          format: date-time
          description: дата создания в формате RFC3339
      example:
        id: "123e4567-e89b-12d3-a456-426614174000"
        projection: "задняя крутая"
        checked: false
        external_id: "123e4567-e89b-12d3-a456-426614174000"
        device_id: 1
        status: "pending"
        create_at: "2021-01-01T00:00:00Z" # RFC3339

    echographics:
      type: object
      description: эхографическая информация
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
          description: id узи
        contors:
          type: string
          description: контуры
          maxLength: 255
        left_lobe_length:
          type: number
          description: длина левого доли
        left_lobe_width:
          type: number
          description: ширина левого доли
        left_lobe_thick:
          type: number
          description: толщина левого доли
        left_lobe_volum:
          type: number
          description: объем левого доли
        right_lobe_length:
          type: number
          description: длина правого доли
        right_lobe_width:
          type: number
          description: ширина правого доли
        right_lobe_thick:
          type: number
          description: толщина правого доли
        right_lobe_volum:
          type: number
          description: объем правого доли
        gland_volum:
          type: number
          description: объем железы
        isthmus:
          type: number
          description: перешеек
        struct:
          type: string
          description: структура
          maxLength: 255
        echogenicity:
          type: string
          description: эхогенность
          maxLength: 255
        regional_lymph:
          type: string
          description: регионарные лимфоузлы
          maxLength: 255
        vascularization:
          type: string
          description: васкуляризация по ЦДК
          maxLength: 255
        location:
          type: string
          description: расположение
          maxLength: 255
        additional:
          type: string
          description: дополнительная информация
          maxLength: 255
        conclusion:
          type: string
          description: заключение
          maxLength: 255
      example:
        id: "123e4567-e89b-12d3-a456-426614174000"
        contors: "контуры"
        left_lobe_length: 100
        left_lobe_width: 100
        left_lobe_thick: 100
        left_lobe_volum: 100
        right_lobe_length: 100
        right_lobe_width: 100
        right_lobe_thick: 100
        right_lobe_volum: 100
        gland_volum: 100
        isthmus: 100
        struct: "квадрат блять"
        echogenicity: "эхогенность"
        regional_lymph: "в правой части"
        vascularization: "выраженная"
        location: "в правой части"
        additional: "пьет курит и ебет"
        conclusion: "грустно"

    node:
      type: object
      description: узел
      required:
        - id
        - ai
        - uzi_id
        - tirads_23
        - tirads_4
        - tirads_5
      properties:
        id:
          type: string
          format: uuid
          description: id узла
        ai:
          type: boolean
          description: признак того, что узел был обработан нейронкой
        uzi_id:
          type: string
          format: uuid
          description: id узи, к которому относится узел
        tirads_23:
          type: number
          maximum: 1.0
          minimum: 0.0
          description: вероятность наличия опухоли в 23-й группе
        tirads_4:
          type: number
          maximum: 1.0
          minimum: 0.0
          description: вероятность наличия опухоли в 4-й группе
        tirads_5:
          type: number
          maximum: 1.0
          minimum: 0.0
          description: вероятность наличия опухоли в 5-й группе
      example:
        id: "123e4567-e89b-12d3-a456-426614174000"
        ai: false
        uzi_id: "123e4567-e89b-12d3-a456-426614174000"
        tirads_23: 0.67
        tirads_4: 0.23
        tirads_5: 0.89

    contor:
      type: array
      description: контур сегмента в формате json
      items:
        type: object
        properties:
          x:
            type: integer
            minimum: 0
            description: x координата точки
          y:
            type: integer
            minimum: 0
            description: y координата точки
      example:
        - x: 100
          y: 100
        - x: 200
          y: 200

    segment:
      type: object
      description: сегмент узла на изображении
      required:
        - id
        - image_id
        - node_id
        - contor
        - tirads_23
        - tirads_4
        - tirads_5
      properties:
        id:
          type: string
          format: uuid
          description: id сегмента
        image_id:
          type: string
          format: uuid
          description: id изображения, к которому относится сегмент
        node_id:
          type: string
          format: uuid
          description: id узла, к которому относится сегмент
        contor:
          $ref: '#/components/schemas/contor'
          description: контур сегмента
        tirads_23:
          type: number
          maximum: 1.0
          minimum: 0.0
          description: вероятность наличия опухоли в 23-й группе
        tirads_4:
          type: number
          maximum: 1.0
          minimum: 0.0
          description: вероятность наличия опухоли в 4-й группе
        tirads_5:
          type: number
          maximum: 1.0
          minimum: 0.0
          description: вероятность наличия опухоли в 5-й группе
      example:
        id: "123e4567-e89b-12d3-a456-426614174000"
        image_id: "123e4567-e89b-12d3-a456-426614174000"
        node_id: "123e4567-e89b-12d3-a456-426614174000"
        contor:
          - x: 100
            y: 100
          - x: 200
            y: 200
        tirads_23: 0.45
        tirads_4: 0.78
        tirads_5: 0.12
    
    image:
      type: object
      description: изображение
      required:
        - id
        - uzi_id
        - page
      properties:
        id:
          type: string
          format: uuid
          description: id изображения
        uzi_id:
          type: string
          format: uuid
          description: id узи, к которому относится изображение
        page:
          type: integer
          description: номер страницы
      example:
        id: "123e4567-e89b-12d3-a456-426614174000"
        uzi_id: "123e4567-e89b-12d3-a456-426614174000"
        page: 1
    
    simpleUuid:
      type: object
      description: uuid
      properties:
        id:
          type: string
          format: uuid
      example:
        id: "123e4567-e89b-12d3-a456-426614174000"
    
    error:
      type: object
      description: ошибка
      properties:
        error:
          type: string
          description: ошибка
      example:
        error: "nya nya nya"

# TODO: описать для auth
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

# TODO: описать через json'ы
  responses:
    Unauthorized:
      description: не авторизован
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"

    ValidationError:
      description: ошибка валидации
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"

    InternalServerError:
      description: внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"


# TODO: описать security после решения по авторизации
paths:
  /uzi:
    post:
      summary: загрузить узи на обработку
      tags:
        - uzi
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: файл узи. **обязательно с .tiff/.png**
                projection:
                  type: string
                  description: проекция узи
                external_id:
                  type: string
                  format: uuid
                  description: внешний id пациента/организации etc.
                device_id:
                  type: integer
                  description: id узи аппарата
              required:
                - file
                - projection
                - external_id
                - device_id
      responses:
        '200':
          description: id узи
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/simpleUuid"
        '500':
          $ref: "#/components/responses/InternalServerError"

  /uzi/{id}:
    get:
      summary: получить узи
      security:
        - BearerAuth: []
      tags:
        - uzi
      parameters:
        - name: id
          in: path
          required: true
          description: id узи
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: узи
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/uzi"
        '500':
          $ref: "#/components/responses/InternalServerError"
    
    patch:
      summary: обновить узи
      security:
        - BearerAuth: []
      tags:
        - uzi
      parameters:
        - name: id
          in: path
          required: true
          description: id узи
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                projection:
                  type: string
                  description: проекция узи
                  maxLength: 255
                checked:
                  type: boolean
                  description: признак того, что узи проверено врачом
              example:
                projection: "52 улица"
                checked: true
      responses:
        '200':
          description: узи
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/uzi"
        '500':
          $ref: "#/components/responses/InternalServerError"

  /uzis/{external_id}:
    get:
      summary: получить узи по внешнему id
      security:
        - BearerAuth: []
      tags:
        - uzi
      parameters:
        - name: external_id
          in: path
          required: true
          description: внешний id пациента/организации etc.
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: узи
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/uzi'
        '500':
          $ref: "#/components/responses/InternalServerError"

  /uzi/echographics/{uzi_id}:
    get:
      summary: получить эхографику uzi
      security:
        - BearerAuth: []
      tags:
        - uzi
      parameters:
        - name: uzi_id
          in: path
          required: true
          description: id узи
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: echographics
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/echographics'
        '500':
          $ref: "#/components/responses/InternalServerError"
    
    patch:
      summary: обновить эхографику
      security:
        - BearerAuth: []
      tags:
        - uzi
      parameters:
        - name: uzi_id
          in: path
          required: true
          description: id узи
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/echographics'
      responses:
        '200':
          description: echographic
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/echographics'
        '500':
          $ref: "#/components/responses/InternalServerError"

  /uzi/device:
    post:
      summary: добавить uzi аппарат
      security:
        - BearerAuth: []
      tags:
        - uzi
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  maxLength: 255
                  description: именование модели узи аппарата
              example:
                name: "Siemens"
      responses:
        '200':
          description: id uzi аппарата
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                properties:
                  id:
                    type: integer
                    description: id uzi аппарата
              example:
                id: 1
        '500':
          $ref: "#/components/responses/InternalServerError"

  /uzi/devices:              
    get:
      summary: получит список uzi апппапапратов
      security:
        - BearerAuth: []
      tags:
        - uzi
      responses:
        '200':
          description: uzi аппараты
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/device"
        '500':
          $ref: "#/components/responses/InternalServerError"

  /uzi/{id}/images:
    get:
      summary: получает списк изображений uzi
      security:
        - BearerAuth: []
      tags:
        - uzi
      parameters:
        - name: id
          in: path
          required: true
          description: id узи
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: images
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/image'
        '500':
          $ref: "#/components/responses/InternalServerError"

  /uzi/image/{id}/nodes-segments:
    get:
      summary: получит узлы и сегменты на указанном изображении
      security:
        - BearerAuth: []
      tags:
        - uzi
      parameters:
        - name: id
          in: path
          required: true
          description: id изображения
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: узлы и сегменты
          content:
            application/json:
              schema:
                type: object
                properties:
                  nodes:
                    type: array
                    items:
                      $ref: '#/components/schemas/node'
                  segments:
                    type: array
                    items:
                      $ref: '#/components/schemas/segment'
        '500':
          $ref: "#/components/responses/InternalServerError"


  /uzi/nodes-segments:
    post:
      summary: добавить узел с сегментами
      security:
        - BearerAuth: []
      tags:
        - uzi
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                node:
                  type: object
                  properties:
                    uzi_id:
                      type: string
                      format: uuid
                    ai:
                      type: boolean
                    tirads_23:
                      type: number
                      maximum: 1.0
                      minimum: 0.0
                    tirads_4:
                      type: number
                      maximum: 1.0
                      minimum: 0.0
                    tirads_5:
                      type: number
                      maximum: 1.0
                      minimum: 0.0
                segments:
                  type: array
                  items:
                    type: object
                    properties:
                      image_id:
                        type: string
                        format: uuid
                      contor:
                        $ref: '#/components/schemas/contor'
                      tirads_23:
                        type: number
                        maximum: 1.0
                        minimum: 0.0
                      tirads_4:
                        type: number
                        maximum: 1.0
                        minimum: 0.0
                      tirads_5:
                        type: number
                        maximum: 1.0
                        minimum: 0.0
      responses:
        '200':
          description: id узла
          content:
            application/json:
              schema:
                type: object
                properties:
                  node_id:
                    type: string
                    format: uuid
                  segment_ids:
                    type: array
                    items:
                      type: string
                      format: uuid
        '500':
          $ref: "#/components/responses/InternalServerError"

  /uzi/{id}/nodes:
    get:
      summary: получить все узлы узи
      security:
        - BearerAuth: []
      tags:
        - uzi
      parameters:
        - name: id
          in: path
          required: true
          description: uzi_id
          schema:
            type: string
      responses:
        '200':
          description: id узла
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/node'
        '500':
          $ref: "#/components/responses/InternalServerError"

  /uzi/nodes/{id}:
    patch:
      summary: обновить узел
      security:
        - BearerAuth: []
      tags:
        - uzi
      parameters:
        - name: id
          in: path
          required: true
          description: id узла
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tirads_23:
                  type: number
                  maximum: 1.0
                  minimum: 0.0
                tirads_4:
                  type: number
                  maximum: 1.0
                  minimum: 0.0
                tirads_5:
                  type: number
                  maximum: 1.0
                  minimum: 0.0
              example:
                tirads_23: 0.67
                tirads_4: 0.23
                tirads_5: 0.89
            
      responses:
        '200':
          description: обновленный узел
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/node'
        '500':
          $ref: "#/components/responses/InternalServerError"

    delete:
      summary: удалить узел
      description: сегменты узла будут также удалены
      security:
        - BearerAuth: []
      tags:
        - uzi
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: узел удален
        '500':
          $ref: "#/components/responses/InternalServerError"

  /uzi/segment:
    post:
      summary: добавить новый сегмент
      security:
        - BearerAuth: []
      tags:
        - uzi
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                image_id:
                  type: string
                  format: uuid
                node_id:
                  type: string
                  format: uuid
                contor:
                  $ref: '#/components/schemas/contor'
                tirads_23:
                  type: number
                  maximum: 1.0
                  minimum: 0.0
                tirads_4:
                  type: number
                  maximum: 1.0
                  minimum: 0.0
                tirads_5:
                  type: number
                  maximum: 1.0
                  minimum: 0.0
      responses:
        '200':
          description: id сегмента
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/simpleUuid"
        '500':
          $ref: "#/components/responses/InternalServerError"

  /uzi/segment/{id}:
    patch:
      summary: обновить сегмент
      security:
        - BearerAuth: []
      tags:
        - uzi
      parameters:
        - name: id
          in: path
          required: true
          description: id сегмента
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                # TODO: добавить контур на обновление
                tirads_23:
                  type: number
                  maximum: 1.0
                  minimum: 0.0
                tirads_4:
                  type: number
                  maximum: 1.0
                  minimum: 0.0
                tirads_5:
                  type: number
                  maximum: 1.0
                  minimum: 0.0
              example:
                tirads_23: 0.67
                tirads_4: 0.23
                tirads_5: 0.89
      responses:
        '200':
          description: обновленный узел
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/segment'
        '500':
          $ref: "#/components/responses/InternalServerError"

    delete:
      summary: удалить сегмент
      description: если у узла не останется сегментов, он будет **удален**
      security:
        - BearerAuth: []
      tags:
        - uzi
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: сегмент удален
        '500':
          $ref: "#/components/responses/InternalServerError"
